### ISSUE TITLE
Problem with lsd

### ISSUE THREAD

**Issue by boazmohar** [JaneliaSciComp/spark-janelia#4]
In [lsd](https://github.com/JaneliaSciComp/spark-janelia/blob/master/spark-janelia-lsf#L273)
There is:
```pyhon
if driverstat is "EXIT" or "DONE":
    drivercomplete = True
```
Should be:
```python
if driverstat is "EXIT" or driverstat is "DONE":
    drivercomplete = True
```
Otherwise it will terminate immediately.

Also, after fixing that it seems that it does not know when the driver exited with status 0.
After waiting for over 30s after the output of the driver was completed it is still waiting and not killing the cluster.

For example with job # 270846 for the driver and # 270839 was the master.

**Comment by stuarteberg** [comment]
This can be closed now (fixed via ff82c39e7606794e6d3c8c01a8b173bd89d017ec).
